on:
  push:
    branches:
      - main
      - "feature/**"
  pull_request:
    branches:
      - '**'
name: Push Event
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    services:
      opensearch:
        image: opensearchproject/opensearch:2.3.0
        ports:
          - "127.0.0.1:9200:9200"
          - "127.0.0.1:9300:9300"
        environment:
          - cluster.name=opensearch-cluster
          - node.name=opensearch-node1
          - network.host=0.0.0.0
          - transport.host=0.0.0.0
          - discovery.type=single-node
          - http.port=9200
          - plugins.security.disabled=true
          - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m" # Set min and max JVM heap sizes to at least 50% of system RAM
      localstack:
        image: localstack/localstack
        env:
          SERVICES: s3,sns,sqs
        ports:
          - 4566:4566
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version-file: ".nvmrc"
          cache: npm
          cache-dependency-path: package.json
      - name: Upgrade npm
        run: npm install -g npm@latest
      - name: Install dependencies
        run: npm install
      - name: Eslint
        run: npm run lint
      - name: Typecheck
        run: npm run typecheck
      - name: Audit
        run: npm audit --omit dev
      - name: Unit tests
        run: npm run test:coverage
      - name: Wait for Elasticsearch
        run: ./bin/wait-for-opensearch/run.sh
      - name: System tests
        run: npm run test:system
      - name: Run build
        run: npm run build
